# Reference: https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

image: ubuntu

version: "{build}"

environment:
  CODECOV: OFF
  COMPILER: GCC
  DOWNLOAD_TAGFILES: OFF
  AIKIDO_BUILD_DIR: "${APPVEYOR_BUILD_FOLDER}"
  matrix:
    - BUILD_TYPE: Debug
      CATKIN_CONFIG_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug -DTREAT_WARNINGS_AS_ERRORS=ON"
    - BUILD_TYPE: Release
      CATKIN_CONFIG_OPTIONS: "-DCMAKE_BUILD_TYPE=Release -DTREAT_WARNINGS_AS_ERRORS=ON"

install:
  - sh: . "${APPVEYOR_BUILD_FOLDER}/.ci/before_install_linux.sh"
  - sh: . "${APPVEYOR_BUILD_FOLDER}/.ci/install_linux.sh"

build_script:
  - sh: . "${APPVEYOR_BUILD_FOLDER}/.ci/script_linux.sh"

on_failure:
  - sh: cat ./build/aikido/Testing/Temporary/LastTest.log
  - sh: cat ./build/aikido/Testing/Temporary/LastTestsFailed.log
  - sh: cat Testing/Temporary/LastTest.log
  - sh: cat Testing/Temporary/LastTestsFailed.log

on_finish:
  - sh: ./scripts/view-all-results.sh test_results
